import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      // flex: 1,
      backgroundColor: "#f9f9f9",
      alignItems: "center",
      justifyContent: "center",
    },
    textFamily: {
      fontFamily: "Verdana",
      fontWeight: "bold",
      fontSize: 12,
    },
    logo: {
      width: 100,
      height: 100,
      // flex:1,
      marginTop: 100,
      marginBottom: 50,
    },
    button: {
      alignSelf: "stretch",
      margin: 20,
      marginTop: 20,
      padding: 10,
      paddingLeft: 135,
      paddingRight: 135,
      backgroundColor: "#2b2b2b",
    },
    buttonText: {
      flexDirection: "row",
      color: "#f9f9f9",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Verdana",
      justifyContent: "center",
      textAlign: "center",
    },
    signButton: {
      fontSize: 12,
      fontFamily: "Verdana",
      color: "#2b2b2b",
    },
    facebookButton: {
      flexDirection: "row",
      alignSelf: "stretch",
      alignItems: "center",
      margin: 20,
      padding: 10,
      paddingLeft: 70,
      paddingRight: 70,
      backgroundColor: "#3B5998",
    },
    googleButton: {
      flexDirection: "row",
      alignSelf: "stretch",
      alignItems: "center",
      marginLeft: 20,
      marginRight: 20,
      padding: 10,
      paddingLeft: 70,
      paddingRight: 70,
      backgroundColor: "#4285f4",
    },
    ButtonText: {
      color: "#2b2b2b",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Verdana",
      flexDirection: "row",
    },
    input: {
      alignSelf: "stretch",
      height: 40,
      margin: 15,
      borderWidth: 1,
      padding: 10,
      borderColor: "#2b2b2b",
    },
    hr: {
      width: 100,
      flex: 1,
      height: 1.5,
      backgroundColor: "#b9b9b9",
      marginTop: 10,
      marginBottom: 10,
    },
    otherLogin: {
      marginTop: 15,
    },
  
    inputSection: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#fff",
    },
  });
  